Hedera <> WalletConnect
hashgraph/hedera-wallet-connect pull request #19
Opened 2024-01-12 05:35 UTC by hgraphql

# Reference implementation
This PR intends to serve as the reference implementation of https://specs.walletconnect.com/2.0/blockchain-rpc/hedera-rpc

## Goal
If the demo apps (wallet or dApp) in this repo work correctly, your integration is solid.

### Background
We appreciate everyone's participation, coordination, and collaboration with https://hips.hedera.com/hip/hip-820.

## Let's keep building
The value (both economic and personal) that we've gained through collaboration and interconnectedness are invaluable assets. By being connected, we unlock the possibilities we can already see.

2024-01-19 19:06 UTC, nathanklick requested changes

2024-01-19 19:06 UTC, nathanklick commented on package.json
> +  "license": "MIT",
The Hedera standard license for all OSS projects is `Apache 2.0`. Please revert this back to an `Apache 2.0` license.

2024-01-19 19:06 UTC, nathanklick commented on LICENSE
Please revert this change. The Hedera standard license for all OSS projects in an `Apache 2.0` license.

2024-01-19 19:12 UTC, nathanklick requested changes

2024-01-19 19:12 UTC, nathanklick commented on .github/workflows/prettier.yml
> +name: prettier
```suggestion
name: Prettier
```

2024-01-19 19:12 UTC, nathanklick commented on .github/workflows/prettier.yml
> +    runs-on: ubuntu-latest
```suggestion
  formatting-check:
    name: Formatting Check
    runs-on: [self-hosted, Linux, medium, ephemeral]
```

2024-01-19 19:12 UTC, nathanklick commented on .github/workflows/prettier.yml
> +      - '*'
```suggestion
on:
  push:
  pull_request:
  
permissions:
  contents: read
```

2024-01-19 19:12 UTC, nathanklick commented on .github/workflows/test.yml
> +    permissions: write-all
```suggestion
    permissions: 
       checks: write
       pull-requests: write
       contents: read
```

2024-01-19 19:42 UTC, hgraphql commented
thanks @nathanklick,

all code changes have been applied

2024-01-22 21:17 UTC, nathanklick commented on .github/dependabot.yml
This file should be restored and updated to include a section for `package-ecosystem: npm`.

2024-01-22 21:28 UTC, hgraphql commented on .github/dependabot.yml
great, thanks @nathanklick 

I've added the file and section.

2024-01-23 17:38 UTC, nathanklick commented on .github/workflows/test.yml
> +  # pull_request:
```suggestion
  pull_request:
```

2024-01-23 17:41 UTC, nathanklick commented on .github/workflows/test.yml
> +        run: npm run test
Run this step only on a forked PR.

```suggestion
      - name: Run tests (Forked PR)
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository && !cancelled() && !failure() }} 
        run: npm run test
```

2024-01-23 17:46 UTC, nathanklick commented on .github/workflows/test.yml
> +      #    test-script: npm run test
Run this step if from a non-forked PR or is triggered by a push to the `main` branch.

```suggestion
      - name: Run tests
        uses: ArtiomTr/jest-coverage-report-action@v2
        if: ${{ ((github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) || github.event_name == 'push') && !cancelled() && !failure() }}
        with:
         test-script: npm run test
```

2024-01-23 17:51 UTC, nathanklick approved these changes
@hgraphql LGTM now, thanks for making all the changes!

2024-01-23 17:52 UTC, hgraphql commented
> @hgraphql LGTM now, thanks for making all the changes!

@nathanklick awesome, thanks for the help!

2024-01-23 17:52 UTC, merged

2024-01-23 17:52 UTC, nathanklick commented
@gregscullard @Ashe-Oro All my concerns are resolved. Please review and merge when you are ready.