chore: add repo maintainers in the CODEOWNERS file
hashgraph/hedera-wallet-connect pull request #384
Opened 2024-12-17 09:34 UTC by PavelSBorisov

**Description**:
Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Related issue(s)**:

Fixes #10 

**Notes for reviewer**:
N/A

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-17 13:32 UTC, andrewb1269hg commented
Line 2 - while we're changing things here, please fix the indent of the teams so it lines up with the lines below it.

2024-12-17 13:33 UTC, andrewb1269hg requested changes
Line 2 - while we're changing things here, please fix the indent of the teams so it lines up with the lines below it.

2024-12-18 20:43 UTC, rbarkerSL approved these changes

2024-12-19 17:00 UTC, andrewb1269hg approved these changes

2024-12-20 01:28 UTC, tmctl approved these changes
lgtm

2024-12-20 01:28 UTC, merged